//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBitly.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyBitleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyBitleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBitly.BLL.Resources.MyBitleResources", typeof(MyBitleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTY_ARG_URL.
        /// </summary>
        public static string EMPTY_ARG_URL {
            get {
                return ResourceManager.GetString("EMPTY_ARG_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPTY_SHORT_URL.
        /// </summary>
        public static string EMPTY_SHORT_URL {
            get {
                return ResourceManager.GetString("EMPTY_SHORT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCEPTION_STORAGE_URL.
        /// </summary>
        public static string EXCEPTION_STORAGE_URL {
            get {
                return ResourceManager.GetString("EXCEPTION_STORAGE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите короткую ссылку..
        /// </summary>
        public static string HashIsNullOrEmptyException {
            get {
                return ResourceManager.GetString("HashIsNullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_ARG_URL.
        /// </summary>
        public static string INVALID_ARG_URL {
            get {
                return ResourceManager.GetString("INVALID_ARG_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка не найдена..
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сократить ссылку..
        /// </summary>
        public static string ShortenUrlException {
            get {
                return ResourceManager.GetString("ShortenUrlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL_NOT_FOUND.
        /// </summary>
        public static string URL_NOT_FOUND {
            get {
                return ResourceManager.GetString("URL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите ссылку..
        /// </summary>
        public static string UrlIsNullOrEmptyException {
            get {
                return ResourceManager.GetString("UrlIsNullOrEmptyException", resourceCulture);
            }
        }
    }
}
